/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as ScanningRouteImport } from './routes/scanning'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as OptimusRouteImport } from './routes/optimus'
import { Route as CodeFixRouteImport } from './routes/code-fix'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FocusSlugRouteImport } from './routes/focus.$slug'

const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanningRoute = ScanningRouteImport.update({
  id: '/scanning',
  path: '/scanning',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimusRoute = OptimusRouteImport.update({
  id: '/optimus',
  path: '/optimus',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeFixRoute = CodeFixRouteImport.update({
  id: '/code-fix',
  path: '/code-fix',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusSlugRoute = FocusSlugRouteImport.update({
  id: '/focus/$slug',
  path: '/focus/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/code-fix': typeof CodeFixRoute
  '/optimus': typeof OptimusRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/scanning': typeof ScanningRoute
  '/solution': typeof SolutionRoute
  '/focus/$slug': typeof FocusSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/code-fix': typeof CodeFixRoute
  '/optimus': typeof OptimusRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/scanning': typeof ScanningRoute
  '/solution': typeof SolutionRoute
  '/focus/$slug': typeof FocusSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/code-fix': typeof CodeFixRoute
  '/optimus': typeof OptimusRoute
  '/quiz': typeof QuizRoute
  '/results': typeof ResultsRoute
  '/scan': typeof ScanRoute
  '/scanning': typeof ScanningRoute
  '/solution': typeof SolutionRoute
  '/focus/$slug': typeof FocusSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/code-fix'
    | '/optimus'
    | '/quiz'
    | '/results'
    | '/scan'
    | '/scanning'
    | '/solution'
    | '/focus/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/code-fix'
    | '/optimus'
    | '/quiz'
    | '/results'
    | '/scan'
    | '/scanning'
    | '/solution'
    | '/focus/$slug'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/code-fix'
    | '/optimus'
    | '/quiz'
    | '/results'
    | '/scan'
    | '/scanning'
    | '/solution'
    | '/focus/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  CodeFixRoute: typeof CodeFixRoute
  OptimusRoute: typeof OptimusRoute
  QuizRoute: typeof QuizRoute
  ResultsRoute: typeof ResultsRoute
  ScanRoute: typeof ScanRoute
  ScanningRoute: typeof ScanningRoute
  SolutionRoute: typeof SolutionRoute
  FocusSlugRoute: typeof FocusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanning': {
      id: '/scanning'
      path: '/scanning'
      fullPath: '/scanning'
      preLoaderRoute: typeof ScanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimus': {
      id: '/optimus'
      path: '/optimus'
      fullPath: '/optimus'
      preLoaderRoute: typeof OptimusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-fix': {
      id: '/code-fix'
      path: '/code-fix'
      fullPath: '/code-fix'
      preLoaderRoute: typeof CodeFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/$slug': {
      id: '/focus/$slug'
      path: '/focus/$slug'
      fullPath: '/focus/$slug'
      preLoaderRoute: typeof FocusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  CodeFixRoute: CodeFixRoute,
  OptimusRoute: OptimusRoute,
  QuizRoute: QuizRoute,
  ResultsRoute: ResultsRoute,
  ScanRoute: ScanRoute,
  ScanningRoute: ScanningRoute,
  SolutionRoute: SolutionRoute,
  FocusSlugRoute: FocusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
